### PR TITLE
config/default.yml: enforce double quotes for stringliterals

### PR DESCRIPTION
**Pull request by commitay**
Opened this for discussion. cc @Homebrew/cask 

> Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.

Is there a reason why we enforce this? It is probably one of the most common errors we see from (new) contributors. 

Enforcing double quotes would also make us more consistent with formulae, which would be nice.

### CODE REVIEW

**Comment by claui** [comment]
Even though I generally oppose double-quote usage for all string literals in Ruby, I support this PR; it merely codifies and enforces Homebrew’s house style, which is already consistently in use for the core code (including Cask) anyway.

@commitay I’m not sure whether this cop also applies to Cask definitions. If so, are we not going to need an accompanying bulk migration on Homebrew/homebrew-cask?

**Comment by commitay** [comment]
> If so, are we not going to need an accompanying bulk migration on Homebrew/homebrew-cask?

Yes but it should be easy with autocorrect.

**Comment by vitorgalvao** [comment]
I don’t see this enough from new users to consider it an issue. The ones that do haven’t run `style` as it’s an auto-fix, so I’ll wager the same it will still happen for those that don’t run `style` and follow the default convention.

In many fonts, `"` looks too similar to (sometimes the same as) `''`. Just look at what happens if I hadn’t told markdown those are code: " vs ''.

I also don’t think parity with formulae should be a goal, here. I mean, I do think it should but in a structural sense, having casks be more “step-by-step” instead of needing `*flight` workarounds. Quote style I don’t see making a difference.

It’s a `rubocop` default, and I like it. In my own coding, it’s often useful in debugging faster as at a glance I can see “will I need to check on this string because there’s something dynamic going on, or can I safely skip it?”.

In sum, there’s a utilitarian choice why both quote styles do different things, and I think we should continue to embrace it. And yes, that does mean I also think HB’s choice is wrong and they should change it.

**Comment by commitay** [comment]
>  there’s a utilitarian choice why both quote styles do different things, and I think we should continue to embrace it.

I don't care which style we use but I think we should have only one style.

"always use double quotes everywhere in Homebrew" 

rather than

"use double quotes sometimes and only in HBC taps"

> And yes, that does mean I also think HB’s choice is wrong and they should change it.

This would require changes across different orgs (Linuxbrew, etc.) rather than just the HBC taps.

**Comment by commitay** [comment]
Closing this for now as there is an open PR importing `rubocop-cask` into `brew`.

**Pull request closed without merging**
